var pages_pt = {
  "about": {
    "title": "Sobre a Igreja de Deus Unida",
    "content": "<p> <em><strong>Louvem ao Eterno! Porque é bom cantar louvores ao nosso Deus; porque é agradável, e o louvor é belo. —Salmo 147:1</strong></em></p>\n<p>O canto tem sido uma parte integrante da adoração a Deus ao longo dos séculos — desde os anjos cantando na criação da terra (Jó 38:7), até os filhos de Israel cantando louvores a Deus pela libertação do exército egípcio (Êxodo 15), até os irmãos do Novo Testamento sendo instruídos a cantar e a fazer melodia a Deus em seus corações (Efésios 5:19). Deus quer que nos deleitemos cantando Seus louvores.</p>\n<p>O livro do Apocalipse revela que o canto continuará a ser uma parte vital da adoração no vindouro Reino de Deus. Apocalipse 14:3 e 15:3 descrevem os santos cantando um novo cântico, bem como o cântico de Moisés e o cântico do Cordeiro.</p>\n<p>Hoje, esta tradição de cantar continua enquanto cumprimos a instrução de Deus, dedicando uma parte significativa de nossos serviços para cantar coletivamente louvores a Ele. Letras inspiradoras nos lembram das magníficas verdades de Sua Palavra. Através do canto de hinos, temos a oportunidade de expressar musicalmente nossas mais profundas emoções de grata apreciação a Deus por Seu plano de salvação para nós e para toda a humanidade. Devido à magnitude de Sua obra maravilhosa e Seu amor incrível, Deus merece nosso mais profundo amor, honra e respeito através do louvor.</p>\n<p>Colossenses 3:16 nos instrui a cantar “salmos, hinos e cânticos espirituais” a Deus com corações agradecidos. Como você notará no sumário, este hinário foi organizado com esta escritura em mente. Que possamos usar este hinário para cumprir a instrução de Deus: “Louvarei ao Eterno com todo o meu coração, na companhia dos retos e na congregação” (Salmo 111:1) e “Cantarei ao Eterno enquanto eu viver; cantarei louvores ao meu Deus enquanto eu existir” (Salmo 104:33).</p>\n<p>&nbsp;</p>"
  },
  "copyright": {
    "title": "Agradecimentos de Direitos Autorais",
    "content": "<p>Um grande esforço foi feito para localizar os proprietários do material protegido por direitos autorais usado neste aplicativo de hinário. Mediante notificação, o editor fará a correção adequada em atualizações subsequentes do aplicativo.</p>"
  },
  "ucg": {
    "title": "Sobre a Igreja de Deus Unida",
    "content": "<h2>Quem Somos</h2>\n<p>Este aplicativo de hinário é publicado pela Igreja de Deus Unida, <em>uma Associação Internacional</em>, que possui ministros e congregações locais nos Estados Unidos e em muitos países ao redor do mundo. Traçamos nossas origens à Igreja que Jesus fundou no início do primeiro século. Seguimos os mesmos ensinamentos, doutrinas e práticas estabelecidas naquela época. Nossa comissão é proclamar o evangelho do Reino vindouro de Deus a todo o mundo como testemunho e ensinar a todas as nações a observar o que Cristo mandou. Se você gostaria de saber mais sobre a Igreja de Deus Unida, visite nosso site em <a href=\"https://www.ucg.org\">www.ucg.org</a>.</p>\n<h2>Aconselhamento Pessoal Disponível</h2>\n<p>Jesus ordenou a Seus seguidores que alimentassem Suas ovelhas. Para cumprir este mandamento, a Igreja de Deus Unida tem congregações em todo o mundo. Nessas congregações, os crentes se reúnem no sábado e nos Dias Santos bíblicos para serem instruídos pelas Escrituras e para comunhão. A Igreja de Deus Unida está comprometida em compreender e praticar o cristianismo do Novo Testamento. Desejamos compartilhar o modo de vida de Deus com aqueles que buscam sinceramente adorar e seguir nosso Salvador, Jesus Cristo. Nossos ministros estão disponíveis para aconselhar, responder a perguntas e explicar a Bíblia.</p>\n<p>Se você gostaria de entrar em contato com um ministro ou visitar uma de nossas congregações, você pode <a href=\"https://www.ucg.org/congregations/all\">ver todas as congregações da UCG</a>, <a href=\"https://www.ucg.org/find-congregation\">pesquisar por código postal</a> ou enviar um e-mail para <a href=\"mailto:info@ucg.org\">info@ucg.org</a> para a congregação mais próxima de você. Se você quiser ligar, consulte a página de <a href=\"https://www.ucg.org/contact/\">contato</a> em ucg.org para nossos números de telefone.</p>\n<p><strong>Endereço para correspondência:</strong> Igreja de Deus Unida, <em>uma Associação Internacional</em>, PO Box 541027, Cincinnati, OH 45254</p>\n<p><strong>Para informações adicionais:</strong> Visite nosso site <a href=\"https://www.ucg.org\">www.ucg.org</a> para baixar ou solicitar qualquer uma de nossas publicações, incluindo edições de <em>As Boas Notícias</em>, dezenas de livretos gratuitos de estudo bíblico, programas Beyond Today e muito mais.</p>\n<p>&nbsp;</p>\n<hr>"
  }
};
