var pages_it = {

    
  "about": {
    "title": "Sulla Chiesa di Dio Unita",
    "content": "<p> <em><strong>Lodate il Signore! Poiché è bello cantare lodi al nostro Dio; poiché è piacevole, e la lode è bella. —Salmo 147:1</strong></em></p>\n<p>Il canto è stato una parte integrante dell'adorazione divina attraverso i secoli — dagli angeli che cantavano alla creazione della terra (Giobbe 38:7), ai figli d'Israele che cantavano lodi a Dio per la liberazione dall'esercito egiziano (Esodo 15), ai fratelli del Nuovo Testamento che venivano istruiti a cantare e a fare melodia a Dio nei loro cuori (Efesini 5:19). Dio vuole che ci dilettiamo nel cantare le sue lodi.</p>\n<p>Il libro dell'Apocalisse rivela che il canto continuerà ad essere una parte vitale dell'adorazione nel Regno di Dio che verrà. Apocalisse 14:3 e 15:3 descrivono i santi che cantano un nuovo cantico, così come il cantico di Mosè e il cantico dell'Agnello.</p>\n<p>Oggi questa tradizione del canto continua mentre adempiamo l'istruzione di Dio dedicando una parte significativa dei nostri servizi a cantare collettivamente lodi a Lui. Testi ispiratori ci ricordano le magnifiche verità della Sua Parola. Attraverso il canto degli inni abbiamo l'opportunità di esprimere musicalmente le nostre più profonde emozioni di grata apprezzamento a Dio per il Suo piano di salvezza per noi e per tutta l'umanità. A causa della grandezza della Sua meravigliosa opera e del Suo incredibile amore, Dio merita il nostro più profondo amore, onore e rispetto attraverso la lode.</p>\n<p>Colossesi 3:16 ci istruisce a cantare \"salmi, inni e cantici spirituali\" a Dio con cuori riconoscenti. Come noterete nell'indice, questo innario è stato organizzato tenendo presente questa scrittura. Possiamo usare questo innario per adempiere l'istruzione di Dio: \"Loderò il Signore con tutto il mio cuore, nell'assemblea dei giusti e nella congregazione\" (Salmo 111:1) e \"Canterò al Signore finché vivrò; canterò lodi al mio Dio finché avrò la mia esistenza\" (Salmo 104:33).</p>\n<p>&nbsp;</p>"
  },
  "copyright": {
    "title": "Riconoscimenti del Copyright",
    "content": "<p>È stato fatto un ampio sforzo per localizzare i proprietari del materiale protetto da copyright utilizzato in questa app inno. In caso di notifica, l'editore apporterà le dovute correzioni nei successivi aggiornamenti dell'app.</p>"
  },
  "ucg": {
    "title": "Sulla Chiesa di Dio Unita",
    "content": "<h2>Chi Siamo</h2>\n<p>Questa applicazione di inno è pubblicata dalla Chiesa di Dio Unita, <em>un'Associazione Internazionale</em>, che ha ministri e congregazioni locali negli Stati Uniti e in molti paesi in tutto il mondo. Tracciamo le nostre origini alla Chiesa che Gesù fondò all'inizio del primo secolo. Seguiamo gli stessi insegnamenti, dottrine e pratiche stabilite allora. La nostra commissione è proclamare il vangelo del Regno di Dio che verrà a tutto il mondo come testimonianza e insegnare a tutte le nazioni a osservare ciò che Cristo ha comandato. Se desideri saperne di più sulla Chiesa di Dio Unita, visita il nostro sito web all'indirizzo <a href=\"https://www.ucg.org\">www.ucg.org</a>.</p>\n<h2>Consiglio Personale Disponibile</h2>\n<p>Gesù comandò ai suoi seguaci di pascere le sue pecore. Per adempiere questo comando, la Chiesa di Dio Unita ha congregazioni in tutto il mondo. In queste congregazioni i credenti si riuniscono il sabato e nei Giorni Santi biblici per essere istruiti dalle Scritture e per fraternizzare. La Chiesa di Dio Unita è impegnata a comprendere e praticare il cristianesimo del Nuovo Testamento. Desideriamo condividere il modo di vita di Dio con coloro che cercano sinceramente di adorare e seguire il nostro Salvatore, Gesù Cristo. I nostri ministri sono disponibili per consigliare, rispondere a domande e spiegare la Bibbia.</p>\n<p>Se desideri contattare un ministro o visitare una delle nostre congregazioni, puoi <a href=\"https://www.ucg.org/congregations/all\">visualizzare tutte le congregazioni della UCG</a>, <a href=\"https://www.ucg.org/find-congregation\">cercare per codice postale</a> o inviare un'e-mail a <a href=\"mailto:info@ucg.org\">info@ucg.org</a> per la congregazione più vicina a te. Se desideri telefonare, consulta la pagina <a href=\"https://www.ucg.org/contact/\">contatti</a> su ucg.org per i nostri numeri di telefono.</p>\n<p><strong>Indirizzo postale:</strong> Chiesa di Dio Unita, <em>un'Associazione Internazionale</em>, PO Box 541027, Cincinnati, OH 45254</p>\n<p><strong>Per informazioni aggiuntive:</strong> Visita il nostro sito web <a href=\"https://www.ucg.org\">www.ucg.org</a> per scaricare o richiedere una qualsiasi delle nostre pubblicazioni, inclusi i numeri di <em>The Good News</em>, dozzine di opuscoli gratuiti per lo studio biblico, programmi Beyond Today e molto altro.</p>\n<p>&nbsp;</p>\n<hr>"
  }


};
