var pages_es = {

    "about": {
        "title": "Acerca de la Iglesia de Dios Unida",
        "content": "<p> <em><strong>¡Alaben al Eterno! Porque es bueno cantar alabanzas a nuestro Dios; porque es agradable, y la alabanza es hermosa. —Salmo 147:1</strong></em></p>\n<p>El canto ha sido una parte integral de la adoración a Dios a través de los siglos —desde los ángeles cantando en la creación de la tierra (Job 38:7), hasta los hijos de Israel cantando alabanzas a Dios por la liberación del ejército egipcio (Éxodo 15), hasta los hermanos del Nuevo Testamento siendo instruidos a cantar y hacer melodía a Dios en sus corazones (Efesios 5:19). Dios quiere que nos deleitemos cantando sus alabanzas.</p>\n<p>El libro de Apocalipsis revela que el canto seguirá siendo una parte vital de la adoración en el venidero Reino de Dios. Apocalipsis 14:3 y 15:3 describen a los santos cantando un cántico nuevo, así como el cántico de Moisés y el cántico del Cordero.</p>\n<p>Hoy esta tradición de cantar continúa mientras cumplimos la instrucción de Dios dedicando una porción significativa de nuestros servicios a cantar colectivamente alabanzas a Él. Las letras inspiradoras nos recuerdan las magníficas verdades de su Palabra. A través del canto de himnos tenemos la oportunidad de expresar musicalmente nuestras más profundas emociones de agradecimiento a Dios por su plan de salvación para nosotros y para toda la humanidad. Debido a la magnitud de su maravillosa obra y su increíble amor, Dios merece nuestro más profundo amor, honor y respeto a través de la alabanza.</p>\n<p>Colosenses 3:16 nos instruye a cantar 'salmos, himnos y cánticos espirituales' a Dios con corazones agradecidos. Como notará en la tabla de contenidos, este himnario ha sido organizado con esta escritura en mente. Que usemos este himnario para cumplir la instrucción de Dios: 'Alabaré al Eterno con todo mi corazón, en la compañía de los rectos y en la congregación' (Salmo 111:1) y 'Cantaré al Eterno mientras viva; cantaré alabanzas a mi Dios mientras tenga mi ser' (Salmo 104:33).</p>\n<p>&nbsp;</p>"
    },
    "copyright": {
        "title": "Agradecimientos de Derechos de Autor",
        "content": "<p>Se ha realizado un gran esfuerzo para localizar a los propietarios del material con derechos de autor utilizado en esta aplicación de himnario. Previa notificación, el editor realizará la corrección adecuada en las subsiguientes actualizaciones de la aplicación.</p>"
    },
    "ucg": {
        "title": "Acerca de la Iglesia de Dios Unida",
        "content": "<h2>Quiénes Somos</h2>\n<p>Esta aplicación de himnario es publicada por la Iglesia de Dios Unida, <em>una Asociación Internacional</em>, que tiene ministros y congregaciones locales en los Estados Unidos y en muchos países alrededor del mundo. Trazamos nuestros orígenes a la Iglesia que Jesús fundó a principios del primer siglo. Seguimos las mismas enseñanzas, doctrinas y prácticas establecidas entonces. Nuestra comisión es proclamar el evangelio del Reino de Dios venidero a todo el mundo como testimonio y enseñar a todas las naciones a observar lo que Cristo mandó. Si desea saber más sobre la Iglesia de Dios Unida, visite nuestro sitio web en <a href=\"https://www.ucg.org\">www.ucg.org</a>.</p>\n<h2>Consejo Personal Disponible</h2>\n<p>Jesús mandó a sus seguidores que apacentaran a sus ovejas. Para cumplir este mandato, la Iglesia de Dios Unida tiene congregaciones en todo el mundo. En estas congregaciones, los creyentes se reúnen el sábado y en los Días Santos bíblicos para ser instruidos de las Escrituras y para confraternizar. La Iglesia de Dios Unida está comprometida a comprender y practicar el cristianismo del Nuevo Testamento. Deseamos compartir el estilo de vida de Dios con aquellos que buscan sinceramente adorar y seguir a nuestro Salvador, Jesucristo. Nuestros ministros están disponibles para aconsejar, responder preguntas y explicar la Biblia.</p>\n<p>Si desea contactar a un ministro o visitar una de nuestras congregaciones, puede <a href=\"https://www.ucg.org/congregations/all\">ver todas las congregaciones de la IGU</a>, <a href=\"https://www.ucg.org/find-congregation\">buscar por código postal</a> o enviar un correo electrónico a <a href=\"mailto:info@ucg.org\">info@ucg.org</a> para encontrar la congregación más cercana a usted. Si desea llamar, por favor consulte la página de <a href=\"https://www.ucg.org/contact/\">contacto</a> en ucg.org para nuestros números de teléfono.</p>\n<p><strong>Dirección postal:</strong> Iglesia de Dios Unida, <em>una Asociación Internacional</em>, PO Box 541027, Cincinnati, OH 45254</p>\n<p><strong>Para información adicional:</strong> Visite nuestro sitio web <a href=\"https://www.ucg.org\">www.ucg.org</a> para descargar o solicitar cualquiera de nuestras publicaciones, incluyendo números de <em>Las Buenas Noticias</em>, docenas de folletos gratuitos de ayuda para el estudio de la Biblia, programas de Beyond Today y mucho más.</p>\n<p>&nbsp;</p>\n<hr>"
    },

};
